parameters:
#    sifue_domain.example.class: Sifue\Bundle\DomainBundle\Example

services:
#    sifue_domain.example:
#        class: %sifue_domain.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
