parameters:
    sifue_domain.user_factory.class: Sifue\Bundle\DomainBundle\Factory\UserFactory

services:
   sifue_domain.user_factory:
       class: %sifue_domain.user_factory.class%
       arguments: []
