parameters:
#    sifue_menu.example.class: Sifue\Bundle\MenuBundle\Example

services:
#    sifue_menu.example:
#        class: %sifue_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
