# jms_security_extra:
#     secure_all_services: false
#     expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: user, roles: [ 'ROLE_USER' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /
        # dev:
        #     pattern:  ^/(_(profiler|wdt)|css|images|js)/
        #     security: false

        # login:
        #     pattern:  ^/demo/secured/login$
        #     security: false

        # secured_area:
        #     pattern:    ^/demo/secured/
        #     form_login:
        #         check_path: /demo/secured/login_check
        #         login_path: /demo/secured/login
        #     logout:
        #         path:   /demo/secured/logout
        #         target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: ROLE_USER }
        - { path: ^/menu, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
