user:
    pattern:  /
    defaults: { _controller: "SifueUserBundle:User:index" }

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "SifueUserBundle:User:show" }

user_show_self:
    pattern:  /show_self
    defaults: { _controller: "SifueUserBundle:User:showSelf" }

user_new:
    pattern:  /new
    defaults: { _controller: "SifueUserBundle:User:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "SifueUserBundle:User:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SifueUserBundle:User:edit" }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "SifueUserBundle:User:update" }
    requirements: { _method: post }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SifueUserBundle:User:delete" }
    requirements: { _method: post }

user_change_password:
    pattern:  /{id}/change_password
    defaults: { _controller: "SifueUserBundle:User:changePassword" }

user_change_password_self:
    pattern:  /change_password_self
    defaults: { _controller: "SifueUserBundle:User:changePasswordSelf" }

user_update_password:
    pattern:  /{id}/update_password
    defaults: { _controller: "SifueUserBundle:User:updatePassword" }
    requirements: { _method: post }
