parameters:
#    sifue_user.example.class: Sifue\Bundle\UserBundle\Example

services:
#    sifue_user.example:
#        class: %sifue_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
