Sifue\Bundle\DomainBundle\Entity\User:
    properties:
        username:
            - NotBlank: ~
        password:
            - NotBlank: ~
        email:
            - NotBlank: ~
        department:
            - NotBlank: ~
